name: .NET Core Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: AoC2022.sln
      Test_Project_Path: AoC2022Tests/AoC2022Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --logger trx
    
    # Collect and publish test results
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.2.0
      with:
        if: always()
        trx_files: "**/*.trx" # Can't get TestResults/**/*.trx to work

    - name: Test Report 2
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
          name: XUnit Tests
          path: "**/*.trx"
          reporter: dotnet-trx
